spring:
    application:
        name: NginxLog
hustack: 
  log: 
    endpoint: https://www.peoplesmedic.com/logs/
    dateFormat: yyyy-MM-dd
    nameFormat: access.%date%.log
    savePath: /logs
  parse:
    timeFormat: '%H:%M:%S'
    dateFormat: '%d/%b/%Y'
    logFormat: '%h %^ %^ [%d:%t %^] "%r" %s %b %^"%R" "%u" "%^" %T'
    savePath: /reports
  notice: 
    