spring:
    application:
        name: NginxLog
hustack: 
  log: 
    endpoint: https://www.peoplesmedic.com/logs/
    dateFormat: yyyy-MM-dd
    nameFormat: access.%date%.log
    savePath: /logs
    cron: '0 23 1 * * ?'
  parse:
    timeFormat: '%H:%M:%S'
    dateFormat: '%d/%b/%Y'
    logFormat: '%h %^ %^ [%d:%t %^] "%r" %s %b %^"%R" "%u" "%^" %T'
    savePath: /reports
    cron: '0 25 1 * * ?'
  notice: 
    cron: '0 28 1 * * ?'
    webhook: https://oapi.dingtalk.com/robot/send?access_token=b271dcd03cceddca8509a3d0efd29b7a88bf86e05f63daa06dd35feb44a24b07